substitutions:
  phase_a_pin: ${phase_a_pin}
  phase_b_pin: ${phase_b_pin}
  phase_c_pin: ${phase_c_pin}

sensor:
  - platform: adc
    pin: ${phase_a_pin}
    id: phase_a_adc
    update_interval: never

  - platform: adc
    pin: ${phase_b_pin}
    id: phase_b_adc
    update_interval: never

  - platform: adc
    pin: ${phase_c_pin}
    id: phase_c_adc
    update_interval: never

script:
  - id: power_meter_source
    mode: single
    then:
      - if:
          condition:
            lambda: 'return network::is_connected();'
          then:
            - lambda: |-
                float rawA = id(phase_a_adc).raw_value;
                float rawB = id(phase_b_adc).raw_value;
                float rawC = id(phase_c_adc).raw_value;

                float calibrated = (rawA * 30.0) + (rawB * 32.0) + (rawC * 29.0);
                id(real_power).publish_state(calibrated);
